### PR TITLE
Fix for issues 12, 11 and 9.

### PR DESCRIPTION
**Pull request by TheDestinyGroup**
Alessandro,

I've add a AesDecryptionResult class (issue 12), renamed the inputs on the DecryptFile functions (issue 11) and fixed the typo in hasEncryptionDataAppendedInInputFile (issue 9).

I'm not sure if I've gone about doing this the right way as this is my first attempt at committing code to GitHub (or any other public/cloud repository) and creating a Pull Request as I've only used private repositories till now.

If I've done something wrong then please feel free to bring that to my attention so I can tell correct it going forward.

As I'm currently using VS 2017 and don't have .NET Standard 2.1 or .NET Core 3.0 installed I was unable to successfully build the solution, but I think I've correctly updated the code including the code which is currently commented out.

I'm also unsure how to go about running the tests in this environment as I'm used to using a build environment which builds the solution the upon commit to the repository and then runs the tests.

Les

### CODE REVIEW

**Comment by TheDestinyGroup** [comment]
Alessandro,

I see that you have an automated build process that checks pull requests.

It identified some issues I relating to the declaration of AesEncryptionResult that I had failed to change to AesDecryptionResult.

It also identified an existing issue in AEAD_AES_256_GCM where EncryptString was being called when it should have been calling DecryptString

I've now corrected those issues and the Pull Request now passes the checks.

Les

PS: If you're happy to accept this pull request then maybe you could consider making a 3.0.1 release which includes these changes and any other you identify as being required.

PPS: The force-pushed commits relate to me updating the comments I used when I originally did the commits so they are more relevant.

**Comment by alecgn** [comment]
Hi Les,
Nicely done, great work!
I'm gonna accept the pull request, thank you by your collaboration!

**Comment by alecgn** [comment]
NuGet package updated -> https://www.nuget.org/packages/CryptHash.Net/3.0.1

**Comment by TheDestinyGroup** [comment]
Alessandro,

Thanks for accepting the pull request. I had hoped my changes would meet your expectations.

I decided to create and then use the AesDecryptionResult class as that seems the right way to properly address the issue I raised with Issue 13 rather than the easy way to address it.

Les

**Pull request merged**
